// OpenLayers 3. See http://openlayers.org/
// License: https://raw.githubusercontent.com/openlayers/ol3/master/LICENSE.md
// Version: v3.0.0-169-g6a1d143

(function(){var f,h=this;function k(a){return void 0!==a}function l(a,b){var c=a.split("."),e=h;c[0]in e||!e.execScript||e.execScript("var "+c[0]);for(var d;c.length&&(d=c.shift());)!c.length&&k(b)?e[d]=b:e[d]?e=e[d]:e=e[d]={}}
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}var n=Date.now||function(){return+new Date};function p(a){var b=q;function c(){}c.prototype=b.prototype;a.s=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.r=function(a,c,g){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function s(a,b){return a<b?-1:a>b?1:0};var t=Array.prototype,u=t.forEach?function(a,b,c){t.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,d="string"==typeof a?a.split(""):a,g=0;g<e;g++)g in d&&b.call(c,d[g],g,a)},v=t.map?function(a,b,c){return t.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,d=Array(e),g="string"==typeof a?a.split(""):a,r=0;r<e;r++)r in g&&(d[r]=b.call(c,g[r],r,a));return d};var w;a:{var z=h.navigator;if(z){var A=z.userAgent;if(A){w=A;break a}}w=""};var B=-1!=w.indexOf("Opera")||-1!=w.indexOf("OPR"),C=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),D=-1!=w.indexOf("Gecko")&&-1==w.toLowerCase().indexOf("webkit")&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE")),E=-1!=w.toLowerCase().indexOf("webkit");function F(){var a=h.document;return a?a.documentMode:void 0}
var G=function(){var a="",b;if(B&&h.opera)return a=h.opera.version,"function"==m(a)?a():a;D?b=/rv\:([^\);]+)(\)|;)/:C?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:E&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(w))?a[1]:"");return C&&(b=F(),b>parseFloat(a))?String(b):a}(),H={};
function I(a){var b;if(!(b=H[a])){b=0;for(var c=String(G).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=Math.max(c.length,e.length),g=0;0==b&&g<d;g++){var r=c[g]||"",Z=e[g]||"",$=RegExp("(\\d*)(\\D*)","g"),aa=RegExp("(\\d*)(\\D*)","g");do{var x=$.exec(r)||["","",""],y=aa.exec(Z)||["","",""];if(0==x[0].length&&0==y[0].length)break;b=s(0==x[1].length?0:parseInt(x[1],10),0==y[1].length?0:parseInt(y[1],10))||s(0==x[2].length,0==y[2].length)||
s(x[2],y[2])}while(0==b)}b=H[a]=0<=b}return b}var J=h.document,ba=J&&C?F()||("CSS1Compat"==J.compatMode?parseInt(G,10):5):void 0;C&&I("9.0");C&&I("9");!E||I("528");D&&I("1.9b")||C&&I("8")||B&&I("9.5")||E&&I("528");D&&!I("8")||C&&I("9");function K(a){this.length=a.length||a;for(var b=0;b<this.length;b++)this[b]=a[b]||0}K.prototype.a=4;K.prototype.b=function(a,b){b=b||0;for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};K.prototype.toString=Array.prototype.join;"undefined"==typeof Float32Array&&(K.BYTES_PER_ELEMENT=4,K.prototype.BYTES_PER_ELEMENT=K.prototype.a,K.prototype.set=K.prototype.b,K.prototype.toString=K.prototype.toString,l("Float32Array",K));function L(a){this.length=a.length||a;for(var b=0;b<this.length;b++)this[b]=a[b]||0}L.prototype.a=8;L.prototype.b=function(a,b){b=b||0;for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};L.prototype.toString=Array.prototype.join;if("undefined"==typeof Float64Array){try{L.BYTES_PER_ELEMENT=8}catch(ca){}L.prototype.BYTES_PER_ELEMENT=L.prototype.a;L.prototype.set=L.prototype.b;L.prototype.toString=L.prototype.toString;l("Float64Array",L)};new Float64Array(3);new Float64Array(3);new Float64Array(4);new Float64Array(4);new Float64Array(4);new Float64Array(16);/*

 Latitude/longitude spherical geodesy formulae taken from
 http://www.movable-type.co.uk/scripts/latlong.html
 Licenced under CC-BY-3.0.
*/
function M(a){this.a=a}M.prototype.offset=function(a,b,c){var e=a[1]*Math.PI/180;b/=this.a;var d=Math.asin(Math.sin(e)*Math.cos(b)+Math.cos(e)*Math.sin(b)*Math.cos(c));return[180*(a[0]*Math.PI/180+Math.atan2(Math.sin(c)*Math.sin(b)*Math.cos(e),Math.cos(b)-Math.sin(e)*Math.sin(d)))/Math.PI,180*d/Math.PI]};var N={};N.degrees=2*Math.PI*(new M(6370997)).a/360;N.ft=.3048;N.m=1;function q(a){this.a=a.code;this.e=a.units;this.b=k(a.c)?a.c:null;this.f=k(a.d)?a.d:null;this.g=k(a.global)?a.global:!1}f=q.prototype;f.h=function(){return this.a};f.i=function(){return this.b};f.k=function(){return this.e};f.j=function(){return N[this.e]};f.l=function(){return this.f};f.n=function(){return this.g};f.o=function(a){this.b=a};f.p=function(a){this.f=a};var O={};
function P(a){da(a);u(a,function(b){u(a,function(a){b!==a&&Q(b,a,R)})})}function ea(a){Q(a,a,R)}function da(a){var b=[];u(a,function(a){b.push(ea(a))})}function Q(a,b,c){a=a.a;b=b.a;a in O||(O[a]={});O[a][b]=c}function R(a,b){var c;if(k(b)){c=0;for(var e=a.length;c<e;++c)b[c]=a[c];c=b}else c=a.slice();return c};!D&&!C||C&&C&&9<=ba||D&&I("1.9.1");C&&I("9");(function(){if(!("HTMLCanvasElement"in h))return!1;try{var a;a=document.createElement("CANVAS");k(void 0)&&(a.width=void 0);k(void 0)&&(a.height=void 0);return null===a.getContext("2d")?!1:!0}catch(b){return!1}})();try{new MouseEvent("click",{buttons:1})}catch(fa){};a:if(!document.implementation||!document.implementation.createDocument){if("undefined"!=typeof ActiveXObject){var S=new ActiveXObject("MSXML2.DOMDocument");if(S){S.resolveExternals=!1;S.validateOnParse=!1;try{S.setProperty("ProhibitDTD",!0),S.setProperty("MaxXMLSize",2048),S.setProperty("MaxElementDepth",256)}catch(ga){}}if(S)break a}throw Error("Your browser does not support creating new documents");};new function(){n()};C||E&&I("525");function T(a){q.call(this,{code:a,units:"m",c:ha,global:!0,d:ia})}p(T);var U=6378137*Math.PI,ha=[-U,-U,U,U],ia=[-180,-85,180,85],V=v("EPSG:3857 EPSG:102100 EPSG:102113 EPSG:900913 urn:ogc:def:crs:EPSG:6.18:3:3857 http://www.opengis.net/gml/srs/epsg.xml#3857".split(" "),function(a){return new T(a)});function ja(a,b,c){var e=a.length;c=1<c?c:2;k(b)||(2<c?b=a.slice():b=Array(e));for(var d=0;d<e;d+=c)b[d]=6378137*Math.PI*a[d]/180,b[d+1]=6378137*Math.log(Math.tan(Math.PI*(a[d+1]+90)/360));return b}
function ka(a,b,c){var e=a.length;c=1<c?c:2;k(b)||(2<c?b=a.slice():b=Array(e));for(var d=0;d<e;d+=c)b[d]=180*a[d]/(6378137*Math.PI),b[d+1]=360*Math.atan(Math.exp(a[d+1]/6378137))/Math.PI-90;return b};function W(a,b){q.call(this,{code:a,units:"degrees",c:X,q:b,global:!0,d:X})}p(W);var X=[-180,-90,180,90],Y=[new W("CRS:84"),new W("EPSG:4326","neu"),new W("urn:ogc:def:crs:EPSG:6.6:4326","neu"),new W("urn:ogc:def:crs:OGC:1.3:CRS84"),new W("urn:ogc:def:crs:OGC:2:84"),new W("http://www.opengis.net/gml/srs/epsg.xml#4326","neu"),new W("urn:x-ogc:def:crs:EPSG:4326","neu")];P(V);P(Y);u(Y,function(a){u(V,function(b){Q(a,b,ja);Q(b,a,ka)})});q.prototype.getCode=q.prototype.h;q.prototype.getExtent=q.prototype.i;q.prototype.getUnits=q.prototype.k;q.prototype.getMetersPerUnit=q.prototype.j;q.prototype.getWorldExtent=q.prototype.l;q.prototype.isGlobal=q.prototype.n;q.prototype.setExtent=q.prototype.o;q.prototype.setWorldExtent=q.prototype.p;})();
